shellEmulator: true

# Temporarily allow trust downgrades for legacy dependencies
trustPolicy: any

packages:
  - webview-ui
  - playground
  - examples/*
onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
